### ISSUE TITLE
Update enum for roles in JSON Schema

### ISSUE THREAD

**Issue by chocolatkey** [readium/guided-navigation#15]
I'm currently writing validation to limit the acceptable roles allowed in a guided navigation document in the [go-toolkit](https://github.com/readium/go-toolkit). The go-toolkit implements SMIL parsing, and based on a [W3C example of a SMIL document](https://www.w3.org/TR/epub/#example-escapable-structures) the name of the table child roles are `table-row` and `table-cell`. However, in the [schema](https://github.com/readium/guided-navigation/blob/main/schema/roles.schema.json), they are `tablerow` and `tablecell`. Can you explain this difference and if there are any others to be aware of when translating from SMIL to a guided nav doc?

**Comment by HadrienGardeur** [comment]
I need to update the JSON Schema now that the roles have been expanded: https://github.com/readium/guided-navigation/blob/main/roles.md

Keep in mind that the roles proposed in this specification are meant to be mapped from HTML, ARIA, DPUB-ARIA and EPUB types, you can use the list of roles as the mapping.
